import ollama


def build_training_data(code_snippets, verbose=False):
    """
    The code snippets will be pass to a server running an LLM to generate training data.

    Args:
        code_snippets (List[Dict[str, Any]]): List of code snippets with metadata.
        verbose (bool): Whether to print the generated training data.

    Returns:
        List[str]: List of training data generated by the LLM.
    """
    training_data = []
    for snippet in code_snippets:
        response_question = ollama.generate(
            model="qwen2.5-coder:7b",
            prompt=f"""
            Given the following code snippet:
            {snippet}

            Write a question that can be answered by the code snippet.

            Examples of questions:
                How does the function foo work?
                How can I use the class Bar?
                What is the purpose of the function baz?
                What is the output of the code snippet?
                What is the size variable in the code snippet?
            """,
        )
        response_summary = ollama.generate(
            model="qwen2.5-coder:7b",
            prompt=f"""
            Given the following code snippet:
            {snippet}

            Write a brief summary of the code snippet.
            The summary should be written in less than three sentences.
            The reader should not have to have knowledge of the code snippet to understand the summary.
            """,
        )
        if verbose:
            print("Code Snippet:")
            for line in snippet["content"].split("\n"):
                print(line)
            print("Question:", response_question["response"])
            print("Summary:", response_summary["response"])
        training_data.append(
            (snippet, response_question["response"], response_summary["response"])
        )
    return training_data
